### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

### ISSUE THREAD

**Issue by rhogg4999** [mossblaser/signal_for_android_decryption#10]
Traceback (most recent call last):
  File "signal_for_android_decryption-main/decrypt_backup.py", line 39, in <module> from Backups_pb2 import BackupFrame, qlStatement  # type: ignore
  File "/cygdrive/c/Users/Robert/Downloads/signal_for_android_decryption-main/Backups_pb2.py", line 21, in <module> _SQLSTATEMENT = DESCRIPTOR.message_types_by_name['SqlStatement']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

I have tried regenerating Backups_pb2.py using protoc but still get the same error.

I don't know what else to try. I am not a python expert in any fashion, sql is more my thing.

**Comment by mossblaser** [comment]
Sorry this has taken me so long to get back to you. This is very much a mystery to me since it seems to be having trouble importing the protobuf-generated Python (so not yet trying to do anything "interesting"!).

I can only guess this could be a cygwin/Windows issue of some kind? Whilst I've never tested this on Windows, I don't know of any reason it shouldn't work there. You might have more success in a different environment, e.g. vanilla python.org Python or WSL2.

**Comment by rhogg4999** [comment]
I finally got around to trying it on Linux Mint using python3 version 3.10.12.

First off I got the same error as before so I rebuilt the Protocol Buffer file.

Now it runs enough to ask for the passphrase but after that the error is:
Protocol message header has no field version

**Comment by mossblaser** [comment]
Perhaps a silly question but you're definitely opening a signal for Android backup? (i.e. not the iOS version?)

**Comment by rhogg4999** [comment]
Yes definitely android.

**Comment by mossblaser** [comment]
> after that the error is:
> Protocol message header has no field version

I wonder if you might be using an out-of-date checkout/branch? Last year the backup format introduced a version field in the backup header -- though support has been in this script since 2023 (e775f96c7 to be specific).

If you run `git rev-parse HEAD` do you see `abd685fae90116bbcc5821ccc3db5525670786de` (the latest version at the time of writing)?

If you are running the latest version, please could you post the full error and backtrace?

---

*Note:* To eliminate this being another Signal backup format change, I've also taken a fresh backup from Signal for Android 7.17.5 and was able to decrypt it under Python 3.12.6 on Arch Linux using the pre-built protobuf file in this repository without any issues.

**Comment by rhogg4999** [comment]
I have taken another clone copy and updated python3. This now works on Linux Mint for me. I updated cygwin on Windows 10 but I still get errors.
I have a working solution on Linux so that's good enough for me.
Thanks for your help and am sorry it wasted your time. Somehow the first cloned copy did not get the latest code or something, who knows.

**Comment by mossblaser** [comment]
No problem at all! It's a useful exercise for me to test it with a latest-version backup now and again! Best of luck sleuthing through the backup!
