### ISSUE TITLE
question about signal desktop backup compatible with android 

### ISSUE THREAD

**Issue by rdmitry0911** [mossblaser/signal_for_android_decryption#2]
Hi, this is a question. I'd like to make exactly opposite thing - to collect signal data from desktop and create a backup out of it compatible with android. Can you give me a clue how would you make this ?

**Comment by mossblaser** [comment]
This would probably be fairly tricky. Whilst the format is simple enough you shouldn't have trouble generating it the contents of the database are most likely hard work to recreate since it is full of implementation details of the app. Whilst I'm sure it'd be technically possible I wouldn't relish the idea!
