### ISSUE TITLE
sms not created

### ISSUE THREAD

**Issue by rhogg4999** [mossblaser/signal_for_android_decryption#3]
Signal backup may have changed recently. Last months backup generates the sms tables but for some reason the backup I created this month, some change in it results in the python script not creating the sms tables.

It just might be me having the problem because of some strange message content that I received this month causing it to have problems decoding.

If so, is there some option I can run that prints out some debug logging to narrow down where the fault is?

Thanks
Rob.

**Comment by mossblaser** [comment]
Interesting...

It's perhaps most likely the database has changed (which my script ought to
be insensitive to). In general my script is quite brittle (by design) and
will crash when the underlying format changes however.

Alas there's no extra debug info available built in but you could always
add some :)

Let me know how you get on or if I can help further (I realise I've not
been too helpful, sorry!)

Jonathan

**Comment by mossblaser** [comment]
...and I recall signal is dropping SMS support so they may be removing that
table for reasons related to that.

**Comment by rhogg4999** [comment]
Good point. I remember reading about them dropping sms. So maybe we need to delete that bit in the code. I will see if I can do that. I am not a python programmer.

**Comment by rhogg4999** [comment]
They may have dropped support for sms ie. unencrypted text messaging but previously all messages where stored in the sms table which is the data that I was extracting. 

I think I can get all the same information out of the mms table. So all good.

Thanks
Rob.
